Feature/kan 21
P4vanzinho/pwafood pull request #1
Opened 2024-03-11 23:01 UTC by P4vanzinho

2024-03-12 16:50 UTC, pavandasilva requested changes

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/page.tsx
> +  console.log(modePage);
console.log esquecido.

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/page.tsx
> +  //Categories request
acho que esqueceu comentário

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/page.tsx
> +          <h1>Crie alguma categoria de alimentos antes de criar um produto.</h1>
Aqui podemos ter um problema, pois não é feito somente para alimentos.

```suggestion
          <h1>Crie alguma categoria antes de criar um produto.</h1>
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    outline-color: ${() => theme.COLORS.PRIMARY};
```suggestion
    outline-color: ${theme.COLORS.PRIMARY};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      color: ${() => theme.COLORS.DARK};
```suggestion
      color: ${theme.COLORS.DARK};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    background-color: ${() => theme.COLORS.LIGHT};
```suggestion
    background-color: ${theme.COLORS.LIGHT};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${() => theme.COLORS.DARK};
```suggestion
    color: ${ theme.COLORS.DARK};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    background-color: ${() => theme.COLORS.LIGHT};
```suggestion
    background-color: ${theme.COLORS.LIGHT};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +  border: 1px solid ${() => theme.COLORS.GRAY};
```suggestion
  border: 1px solid ${theme.COLORS.GRAY};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${() => theme.COLORS.DARK};
```suggestion
    color: ${theme.COLORS.DARK};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      color: ${() => theme.COLORS.GRAY};
```suggestion
      color: ${heme.COLORS.GRAY};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      background-color: ${() => theme.COLORS.GRAY};
```suggestion
      background-color: ${theme.COLORS.GRAY};
```

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    background-color: ${() => theme.COLORS.GRAY};
Considere tirar todos essas funções antes de setar as cores como citado nos exemplos de outros comentários do PR.

2024-03-12 16:50 UTC, pavandasilva commented on public/ArrowDown.svg
Não consegui identificar onde esse svg foi utilizado no seu PR. Verifique por favor e remova se eu estiver correto.

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/novo-produto/page.tsx
acho que não precisamos dessa page aqui.

Tempos em (admin-routes) -> produto/[[Slug]]  . Se você olhar nessa page é possível detectar se é uma edicão de produto ou um cadastro de produto. A lógica do novo produto deve ir para essa page (admin-routes) -> produto/[[Slug]] .

Fazendo isso você poderá reaproveitar toda a tela, tanto para o registro quanto para a edição.

2024-03-12 16:50 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/novo-produto/page.tsx
acho que não precisamos dessa page aqui.

Tempos em (admin-routes) -> produto/[[Slug]]  . Se você olhar nessa page é possível detectar se é uma edicão de produto ou um cadastro de produto. A lógica do novo produto deve ir para essa page (admin-routes) -> produto/[[Slug]] .

Fazendo isso você poderá reaproveitar toda a tela, tanto para o registro quanto para a edição.

2024-03-12 16:50 UTC, pavandasilva commented on src/app/components/ProductPage/index.tsx
Fiquei confuso. Tem uma page dentro da pasta components. 
E também não entendi por que todo esse conteúdo não está em painel-adminstrativo /(admin-routes)/produto/[[slug]]

2024-03-12 16:58 UTC, pavandasilva commented on package.json
> +    "@react-input/mask": "^1.0.22",
acho que não está sendo utilizado em nenhum lugar essa lib que você instalou.

2024-03-12 17:27 UTC, pavandasilva requested changes

2024-03-12 17:27 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/novo-produto/page.tsx
Por favor. Dar gitpull origin develop na nessa branch para voc^poder utilizar os inputs com masks.

Remover a  funcao handleInputPrice desse arquivo e  alterar o uso dos inputs desse arquivo.
Basta subistituir o ``<input ....`` por ``<Input ``.  No caso do input de dinheiro trocar o type para "currency"

2024-03-12 23:50 UTC, P4vanzinho commented on src/app/components/ProductPage/index.tsx
Sobre isso, eu percebi que o businessId vindo da session, renderiza após a renderização da page. Em caso de acessar a página em questão em fluxo normal, sem dar f5 na página, não dispara nenhum erro, mas caso atualize a página, acusa que businessId está undefined, como solução, coloquei o conteúdo na página dentro de um componente, e adicionei passei businessId como propriedade desse componente. A partir disso, fiz uma condicional para renderizar o Container, apenas se businessId tiver valor :

`{!!businessId ? (
        <ProductPage
          modePage={modePage}
          businessId={businessId}
          productId={props?.params?.slug}
        />
`

obs : tentei colocar esse condicional na própria pagina, mas não deu certo, e não entendi muito bem o motivo.

2024-03-13 20:52 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${ theme.COLORS.DARK};
assim acho que nao funciona. Está sobrando um espaço na frente do "t"

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      color: ${ theme.COLORS.GRAY};
sobrando espaço na frente do "t¨ . Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      color: ${ theme.COLORS.DARK};
sobrando espaço na frente do "t". Isso está funcionando.

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +        color: ${ theme.COLORS.GRAY};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +      color: ${ theme.COLORS.DARK};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +  border: 1px solid ${ theme.COLORS.LIGHT};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${ theme.COLORS.DARK};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +  background: #b3b3b3;
usando cor fixa. Use uma cor do thema ou adicione essa cor no thema.

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    background-color: ${ theme.COLORS.LIGHT};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    background-color: ${ theme.COLORS.LIGHT};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${ theme.COLORS.DARK};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    outline: 2px solid ${ theme.COLORS.ERROR};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/produto/[[...slug]]/styles.ts
> +    color: ${ theme.COLORS.ERROR};
sobrando espaço na frente do "t". Isso está funcionando?

2024-03-13 20:52 UTC, rogeriopavan commented on public/ArrowDown.svg
Esse arquivo está sendo utilizado?

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/painel-administrativo/(admin-routes)/novo-produto/page.tsx
a pasta novo-produto não foi deletada.

2024-03-13 20:52 UTC, pavandasilva commented on src/app/painel-administrativo/(admin-routes)/novo-produto/page.tsx
a pasta novo-produto não foi deletada.

2024-03-13 20:52 UTC, rogeriopavan commented on src/app/components/ProductPage/index.tsx
Ok. Vou testar aqui prá entender o que está acontencendo.

2024-03-13 21:33 UTC, pavandasilva commented on src/app/components/ProductPage/index.tsx
Tomando por base da maneira que está feito em components/ProductPage vi que vc está tentando já que o componente inicia já buscar o produto e as categorias 
![image](https://github.com/P4vanzinho/pwafood/assets/26095712/2a0505b6-f393-4d14-b3ad-24a1f9eb4482)

Provavelmente vc tinha feito o mesmo na página que chama esse componente. Não é mesmo. O que acontece é que esse useFoodFetch, se passado os parametros em sua declaração, já executa assim que o componente/page é iniciado, então o erro ocorre porque o business id pode não estar disponível no momento da renderização do componente/page.  

Aqui você deveria executar o request para a api, somente depois que o business id estivesse disponível, veja:

`useEffect(() => {
    if (!businessId) {
      return;
    }

    categoriesRequest({
      endPoint: EndpointFoodApiEnum.PRODUCT_CATEGORY,
      method: 'GET',
      params: {
        injectProducts: true,
        hasProducts: true,
        businessId,
      },
      token: user.token,
    });
  }, [businessId, user, categoriesRequest]);

  const { data: categories, request: categoriesRequest } =
    useFoodFetch<FoodApiCategory[]>();

  useEffect(() => {
    if (!businessId) {
      return;
    }

    productRequest({
      endPoint: EndpointFoodApiEnum.PRODUCT,
      method: 'GET',
      params: {
        businessId,
        productId,
      },
      token: user.token,
    });
  }, [businessId, user, productRequest]);

  const { data: product, productRequest } = useFoodFetch<FoodApiProduct>();`

2024-03-13 21:40 UTC, pavandasilva commented on src/app/components/ProductPage/index.tsx
`const { data: categories, request: categoriesRequest } =
    useFoodFetch<FoodApiCategory[]>();

  useEffect(() => {
    if (!businessId) {
      return;
    }

    categoriesRequest({
      endPoint: EndpointFoodApiEnum.PRODUCT_CATEGORY,
      params: {
        injectProducts: true,
        hasProducts: true,
        businessId,
      },
      token: user.token,
    });
  }, [businessId, user, categoriesRequest]);`

2024-03-13 21:52 UTC, pavandasilva commented on src/app/components/ProductPage/index.tsx
veja também que no caso de chamar o useFoodFetch usando a funcao request, não é necessario passar o parametro "token" e nem o "shouldUseToken", pois por default essa funcão já pega o token da session. Veja:
![image](https://github.com/P4vanzinho/pwafood/assets/26095712/0436a0be-6e57-45f9-9697-bb4b6767014a)

2024-03-14 18:34 UTC, pavandasilva approved these changes

2024-03-14 20:26 UTC, merged